version: '3.8'

services:
  # MySQL数据库
  mysql:
    image: mysql:8.0
    container_name: trading_mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: trading_bot
      MYSQL_USER: trader
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./migrations:/docker-entrypoint-initdb.d
    command: --default-authentication-plugin=mysql_native_password
    networks:
      - trading_network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  # Redis缓存
  redis:
    image: redis:7-alpine
    container_name: trading_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - trading_network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      timeout: 5s
      retries: 5

  # Redis管理界面（可选）
  redis-commander:
    image: rediscommander/redis-commander:latest
    container_name: trading_redis_commander
    environment:
      REDIS_HOSTS: local:redis:6379
    ports:
      - "8081:8081"
    networks:
      - trading_network
    depends_on:
      - redis

  # phpMyAdmin数据库管理界面（可选）
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: trading_phpmyadmin
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_USER: trader
      PMA_PASSWORD: password
    ports:
      - "8080:80"
    networks:
      - trading_network
    depends_on:
      mysql:
        condition: service_healthy

volumes:
  mysql_data:
    driver: local
  redis_data:
    driver: local

networks:
  trading_network:
    driver: bridge
